### ISSUE TITLE
[Bug]: MiniCPM接入vllm测评， type `cpm_dragonfly` but Transformers does not recognize this architecture.

### ISSUE THREAD

**Issue by R0k1e** [OpenBMB/MiniCPM#107]
### Is there an existing issue ? / 是否已有相关的 issue ?

- [X] I have searched, and there is no existing issue. / 我已经搜索过了，没有相关的 issue。

### Describe the bug / 描述这个 bug

依照README进行模型对vllm的适配，在安装完环境以及转换模型后，使用README中的示例会报错。
Transformers为最新安装，不存在版本过旧问题。
Traceback (most recent call last):
  File "\~/miniconda3/envs/ultraeval-12/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1155, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
                   ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\~/miniconda3/envs/ultraeval-12/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 852, in __getitem__
    raise KeyError(key)
KeyError: 'cpm_dragonfly'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\~/MiniCPM/inference/vllm/examples/infer_cpm/inference.py", line 43, in <module>
    llm = LLM(model=args.model_path, tensor_parallel_size=1, dtype='bfloat16')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\~/miniconda3/envs/ultraeval-12/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 93, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\~/miniconda3/envs/ultraeval-12/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 225, in from_engine_args
    engine_configs = engine_args.create_engine_configs()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\~/miniconda3/envs/ultraeval-12/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 187, in create_engine_configs
    model_config = ModelConfig(self.model, self.tokenizer,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\~/miniconda3/envs/ultraeval-12/lib/python3.11/site-packages/vllm/config.py", line 91, in __init__
    self.hf_config = get_config(self.model, trust_remote_code, revision)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\~/miniconda3/envs/ultraeval-12/lib/python3.11/site-packages/vllm/transformers_utils/config.py", line 40, in get_config
    raise e
  File "\~/miniconda3/envs/ultraeval-12/lib/python3.11/site-packages/vllm/transformers_utils/config.py", line 28, in get_config
    config = AutoConfig.from_pretrained(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\~/miniconda3/envs/ultraeval-12/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1157, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `cpm_dragonfly` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.


### To Reproduce / 如何复现

1. 按照以下命令创建环境
``` bash
conda activate ultraeval-12 python==3.11.8
conda activate ultraeval-12
pip3 install torch --upgrade --index-url https://download.pytorch.org/whl/cu121
git clone https://github.com/OpenBMB/MiniCPM.git
cd MiniCPM
pip install inference/vllm
```
2. 下载MiniCPM-2B-sft-bf16，并将其转换成vllm格式
``` bash
python inference/convert_hf_to_vllmcpm.py --load ./MiniCPM-2B-sft-bf16 --save ./MiniCPM-2B-sft-bf16-vllm
```
3. 执行测试样例
```shell
cd inference/vllm/examples/infer_cpm
python inference.py --model_path  ./MiniCPM-2B-sft-bf16-vllm --prompt_path prompts/prompt_demo.txt
```
出现如上bug

### Expected behavior / 期望的结果

期望样例中的输出

### Screenshots / 截图

_No response_

### Environment / 环境

```shell
- OS: Ubuntu 20.04.6 LTS
- Pytorch: 2.2.1+cu121
- CUDA: CUDA 12.1
- Device: A100 80G
```


### Additional context / 其他信息

_No response_

**Comment by R0k1e** [comment]
#9 Fix this problem. 建议将版本添加到README
