### ISSUE TITLE
CUDA out of memory when inference MiniCPM-2B-dpo-bf16 on RTX 2080 Ti

### ISSUE THREAD

**Issue by drriguz** [OpenBMB/MiniCPM#148]
Hi, 
I'm trying to run run MiniCPM-2B model using the code provided in [快速上手](https://github.com/OpenBMB/MiniCPM?tab=readme-ov-file#2), however, I got `CUDA out of memory` error. Since it's only a 2B model and bf16, typically requires 2x2=4G memory, RTX 2080 Ti has 12G and should be enough for it.

```bash
python3 minicpm-2b.py
Traceback (most recent call last):
  File "/home/kas/minicpm/minicpm-2b.py", line 7, in <module>
    model = AutoModelForCausalLM.from_pretrained(path, torch_dtype=torch.bfloat16, device_map='cuda', trust_remote_code=True)
  File "/home/kas/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/home/kas/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3850, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/kas/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4284, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/kas/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 805, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/home/kas/.local/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 347, in set_module_tensor_to_device
    new_value = value.to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.00 MiB. GPU
```

```bash
nvidia-smi
Fri Jun  7 13:35:17 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti     On  | 00000000:85:00.0 Off |                  N/A |
| 36%   28C    P8              20W / 250W |      0MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

```python
cat minicpm-2b.py
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
torch.manual_seed(0)

path = './models/openbmb/MiniCPM-2B-dpo-bf16'
tokenizer = AutoTokenizer.from_pretrained(path)
model = AutoModelForCausalLM.from_pretrained(path, torch_dtype=torch.bfloat16, device_map='cuda', trust_remote_code=True)

responds, history = model.chat(tokenizer, "山东省最高的山是哪座山, 它比黄山高还是矮？差距多少？", temperature=0.5, top_p=0.8, repetition_penalty=1.02)
print(responds)
```

**Comment by LDLINGLINGLING** [comment]
你查看了你的文件夹中是否确实为minicpm的模型呢，换句话说你文件夹中最大的模型大小是多少。

**Comment by LDLINGLINGLING** [comment]
torch，transformers，cuda，nvidia driver版本都看一下吧
