### ISSUE TITLE
在手机端输入长文本报告维度不对错误

### ISSUE THREAD

**Issue by rudaoshi** [OpenBMB/MiniCPM#154]
输入约1134字，错误信息如下

MLCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: TVMError: Check failed: value->shape[0] <= max_cache_size - num_attention_sinks (768 vs. 764) : dim 0 of value too large
Stack trace:
  File "/Users/acha/Desktop/mlc-MiniCPM/3rdparty/tvm/src/runtime/relax_vm/lm_support.cc", line 124

	at org.apache.tvm.Base.checkCall(Base.java:173)
	at org.apache.tvm.Function.invoke(Function.java:130)
	at com.modelbest.mlcllm.ChatModule.prefill(ChatModule.java:55)
	at com.modelbest.minicpm.AppViewModel$ChatState$requestGenerate$1$3.invoke(AppViewModel.kt:665)
	at com.modelbest.minicpm.AppViewModel$ChatState$requestGenerate$1$3.invoke(AppViewModel.kt:665)
	at com.modelbest.minicpm.AppViewModel$ChatState.callBackend(AppViewModel.kt:516)
	at com.modelbest.minicpm.AppViewModel$ChatState.requestGenerate$lambda$5(AppViewModel.kt:665)
	at com.modelbest.minicpm.AppViewModel$ChatState.$r8$lambda$yk6a3ARBHb2puBgO5yGFGVmJ5V4(Unknown Source:0)
	at com.modelbest.minicpm.AppViewModel$ChatState$$ExternalSyntheticLambda4.run(Unknown Source:10)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

Error message:
TVMError: Check failed: value->shape[0] <= max_cache_size - num_attention_sinks (768 vs. 764) : dim 0 of value too large
Stack trace:
  File "/Users/acha/Desktop/mlc-MiniCPM/3rdparty/tvm/src/runtime/relax_vm/lm_support.cc", line 124

**Comment by LDLINGLINGLING** [comment]
mlc已经不再维护了，请使用llama.cpp吧
