### ISSUE TITLE
[Bug]: The checkpoint you are trying to load has model type `cpm_dragonfly` but Transformers does not recognize this architecture. 

### ISSUE THREAD

**Issue by uRENu** [OpenBMB/MiniCPM#155]
### Is there an existing issue ? / 是否已有相关的 issue ?

- [X] I have searched, and there is no existing issue. / 我已经搜索过了，没有相关的 issue。

### Describe the bug / 描述这个 bug

加载微调后的MiniCPM-2B-dpo-bf16模型进行vllm推理时遇到报错‘cpm_dragonfly’：
Traceback (most recent call last):
File "/home/jeeves/.local/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 951, in from_pretrained
config_class = CONFIG_MAPPING[config_dict["model_type"]]
File "/home/jeeves/.local/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 653, in __getitem__
raise KeyError(key)
KeyError: 'cpm_dragonfly'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/local/apps/large_model_predict/open_llm_infer/llm_infer_vllm.py", line 252, in <module>
llm_infer(sft_args)
File "/local/apps/large_model_predict/open_llm_infer/llm_infer_vllm.py", line 122, in llm_infer
llm = LLM(model=args.ckpt_dir, trust_remote_code=True, seed=42, tensor_parallel_size=torch.cuda.device_count())
File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 118, in __init__
self.llm_engine = LLMEngine.from_engine_args(
File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 257, in from_engine_args
engine_config = engine_args.create_engine_config()
File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 464, in create_engine_config
model_config = ModelConfig(
File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/config.py", line 107, in __init__
self.hf_config = get_config(self.model, trust_remote_code, revision,
File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/transformers_utils/config.py", line 38, in get_config
raise e
File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/transformers_utils/config.py", line 23, in get_config
config = AutoConfig.from_pretrained(
File "/home/jeeves/.local/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 953, in from_pretrained
raise ValueError(
ValueError: The checkpoint you are trying to load has model type `cpm_dragonfly` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
Inferring failed, please check log

### To Reproduce / 如何复现

python inference/inference_vllm.py --model_path <hf_repo_path> --prompt_path prompts/prompt_demo.txt

### Environment / 环境

```shell
xformers-0.0.25
vllm-0.4.1 
vllm-nccl-cu12-2.18.1.0.3.0
tokenizers-0.19.1 
torch-2.2.1 
transformers-4.41.2
accelerate-0.31.0
```

**Comment by LDLINGLINGLING** [comment]
你好，请问你是用什么进行的微调，另外能否看下你微调后的config中
"_name_or_path": "openbmb/CPM-2B",
    "architectures": [
        "MiniCPMForCausalLM"
    ],
这两项参数是否正确

**Comment by uRENu** [comment]
> "MiniCPMForCausalLM"

我这边微调后的config如下：
{'_dtype': 'bf16', 'activate_fn': 'silu', 'architectures': ['CPMDragonflyForCausalLM'], 'base': 10000, 'dim_ff': 5760, 'dim_head': 64, 'dim_model': 2304, 'dim_model_base': 256, 'dropout_p': 0.0, 'eps': 1e-05, 'init_std': 0.1, 'model_type': 'cpm_dragonfly', 'num_heads': 36, 'num_kv_heads': 36, 'num_layers': 40, 'orig_max_length': 8192, 'pose_prob': 0.0, 'pose_scaling_factor': 1.0, 'qk_norm': False, 'rope_scaling_factor': 1, 'rope_scaling_type': '', 'scale': True, 'scale_depth': 1.4, 'scale_emb': 12, 'tie_lm_head': True, 'tp': 0, 'transformers_version': '4.35.0', 'vocab_size': 122753}

**Comment by LDLINGLINGLING** [comment]
architectures': ['CPMDragonflyForCausalLM']，你可以看到这个模型的架构已经不是minicpmforCausalLM，这将导致报错
