### ISSUE TITLE
[Feature Request]: 可以取消每次加载模型都需要联网check revision吗？Could the check revision be cancelled before loading the model?

### ISSUE THREAD

**Issue by Yonggie** [OpenBMB/MiniCPM#168]
### Feature request  / 功能建议

你好，不太清楚在哪里修改。。

full log：
```
Traceback (most recent call last):
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/urllib3/connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f1db56d3e50>: Failed to resolve 'www.modelscope.cn' ([Errno -3] Temporary failure in name resolution)

**Comment by zh-zheng** [comment]
你好，如果是在无网环境中，建议提前将模型下载好，并将模型加载路径直接指向本地路径。
