### ISSUE TITLE
[Bug]: RuntimeError: CUDA error: out of memory CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by wm19999** [OpenBMB/MiniCPM#78]
### Is there an existing issue ? / 是否已有相关的 issue ?

- [X] I have searched, and there is no existing issue. / 我已经搜索过了，没有相关的 issue。

### Describe the bug / 描述这个 bug

将模型下载到本地文件夹中进行微调，但是出现报错，下面是我设置的
lora_finetune.sh:
deepspeed --include localhost:0 finetune.py \
    --model_name_or_path /home/amos/my_folder/MiniCPM-old/miniCPM-bf16 \
    --output_dir /home/amos/my_folder/MiniCPM-old/$formatted_time/ \
    --train_data_path /home/amos/my_folder/MiniCPM-old/tokenizer/train_data_chatml.json \
    --eval_data_path /home/amos/my_folder/MiniCPM-old/tokenizer/test_data_chatml.json \
    --learning_rate 1e-3 --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 --fp16 --use_lora \
    --gradient_accumulation_steps 1 --warmup_steps 100 \
    --max_steps 3000 --weight_decay 0.01 \
    --evaluation_strategy steps --eval_steps 500 \
    --save_strategy steps --save_steps 500 --seed 42 \
    --log_level info --logging_strategy steps --logging_steps 10 \
    --deepspeed /home/amos/my_folder/MiniCPM-old/finetune/configs/ds_config_zero3_offload.json
   

使用的显卡是RTX4090，内存24G，使用的微调数据集为：AdvertiseGen.tar.gz。具体报错如下：
Traceback (most recent call last):
  File "/home/amos/my_folder/MiniCPM-old/finetune/finetune.py", line 182, in <module>
    model, tokenizer = load_model_and_tokenizer(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amos/my_folder/MiniCPM-old/finetune/finetune.py", line 135, in load_model_and_tokenizer
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amos/anaconda3/envs/pytorch_2.1.1_llm/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amos/anaconda3/envs/pytorch_2.1.1_llm/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3594, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amos/anaconda3/envs/pytorch_2.1.1_llm/lib/python3.11/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 509, in wrapper
    f(module, *args, **kwargs)
  File "/home/amos/.cache/huggingface/modules/transformers_modules/miniCPM-bf16/modeling_minicpm.py", line 1124, in __init__
    self.model = MiniCPMModel(config)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/amos/anaconda3/envs/pytorch_2.1.1_llm/lib/python3.11/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 509, in wrapper
    f(module, *args, **kwargs)
  File "/home/amos/.cache/huggingface/modules/transformers_modules/miniCPM-bf16/modeling_minicpm.py", line 970, in __init__
    [MiniCPMDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
  File "/home/amos/.cache/huggingface/modules/transformers_modules/miniCPM-bf16/modeling_minicpm.py", line 970, in <listcomp>
    [MiniCPMDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amos/anaconda3/envs/pytorch_2.1.1_llm/lib/python3.11/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 509, in wrapper
    f(module, *args, **kwargs)
  File "/home/amos/.cache/huggingface/modules/transformers_modules/miniCPM-bf16/modeling_minicpm.py", line 769, in __init__
    self.mlp = MiniCPMMLP(config)
               ^^^^^^^^^^^^^^^^^^
  File "/home/amos/anaconda3/envs/pytorch_2.1.1_llm/lib/python3.11/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 509, in wrapper
    f(module, *args, **kwargs)
  File "/home/amos/.cache/huggingface/modules/transformers_modules/miniCPM-bf16/modeling_minicpm.py", line 258, in __init__
    self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amos/anaconda3/envs/pytorch_2.1.1_llm/lib/python3.11/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 519, in wrapper
    self._post_init_method(module)
  File "/home/amos/anaconda3/envs/pytorch_2.1.1_llm/lib/python3.11/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1054, in _post_init_method
    self._zero_init_param(param)
  File "/home/amos/anaconda3/envs/pytorch_2.1.1_llm/lib/python3.11/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1013, in _zero_init_param
    param.partition()
  File "/home/amos/anaconda3/envs/pytorch_2.1.1_llm/lib/python3.11/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1328, in partition
    self._partition(param_list, has_been_updated=has_been_updated)
  File "/home/amos/anaconda3/envs/pytorch_2.1.1_llm/lib/python3.11/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1477, in _partition
    self._partition_param(param, has_been_updated=has_been_updated)
  File "/home/amos/anaconda3/envs/pytorch_2.1.1_llm/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amos/anaconda3/envs/pytorch_2.1.1_llm/lib/python3.11/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1549, in _partition_param
    partitioned_tensor = get_accelerator().pin_memory(partitioned_tensor)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amos/anaconda3/envs/pytorch_2.1.1_llm/lib/python3.11/site-packages/deepspeed/accelerator/cuda_accelerator.py", line 267, in pin_memory
    return tensor.pin_memory()
           ^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2024-02-29 15:00:41,609] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 236954
[2024-02-29 15:00:41,609] [ERROR] [launch.py:321:sigkill_handler] ['/home/amos/anaconda3/envs/pytorch_2.1.1_llm/bin/python', '-u', 'finetune.py', '--local_rank=0', '--model_name_or_path', '/home/amos/my_folder/MiniCPM-old/miniCPM-bf16', '--output_dir', '/home/amos/my_folder/MiniCPM-old/20240229150035/', '--train_data_path', '/home/amos/my_folder/MiniCPM-old/tokenizer/train_data_chatml.json', '--eval_data_path', '/home/amos/my_folder/MiniCPM-old/tokenizer/test_data_chatml.json', '--learning_rate', '1e-3', '--per_device_train_batch_size', '1', '--per_device_eval_batch_size', '1', '--fp16', '--use_lora', '--gradient_accumulation_steps', '1', '--warmup_steps', '100', '--max_steps', '3000', '--weight_decay', '0.01', '--evaluation_strategy', 'steps', '--eval_steps', '500', '--save_strategy', 'steps', '--save_steps', '500', '--seed', '42', '--log_level', 'info', '--logging_strategy', 'steps', '--logging_steps', '10', '--deepspeed', '/home/amos/my_folder/MiniCPM-old/finetune/configs/ds_config_zero3_offload.json'] exits with return code = 1

### To Reproduce / 如何复现

deepspeed --include localhost:0 finetune.py \
    --model_name_or_path /home/amos/my_folder/MiniCPM-old/miniCPM-bf16 \
    --output_dir /home/amos/my_folder/MiniCPM-old/$formatted_time/ \
    --train_data_path /home/amos/my_folder/MiniCPM-old/tokenizer/train_data_chatml.json \
    --eval_data_path /home/amos/my_folder/MiniCPM-old/tokenizer/test_data_chatml.json \
    --learning_rate 1e-3 --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 --fp16 --use_lora \
    --gradient_accumulation_steps 1 --warmup_steps 100 \
    --max_steps 3000 --weight_decay 0.01 \
    --evaluation_strategy steps --eval_steps 500 \
    --save_strategy steps --save_steps 500 --seed 42 \
    --log_level info --logging_strategy steps --logging_steps 10 \
    --deepspeed /home/amos/my_folder/MiniCPM-old/finetune/configs/ds_config_zero3_offload.json

(pytorch_2.1.1_llm) amos@DESKTOP-OR1VC42:~/my_folder/MiniCPM-old/finetune$ bash lora_finetune.sh

### Expected behavior / 期望的结果

能够正常使用lora_finetune.sh进行微调

### Screenshots / 截图

![微信图片_20240229152342](https://github.com/OpenBMB/MiniCPM/assets/86055438/de6adde5-18c5-4450-bee0-e7881661439d)

### Environment / 环境

```shell
- OS: [Ubuntu 20.04]
- Pytorch: [torch 2.1.1]
- CUDA: [CUDA 11.8]
- Device: [RTX4090单卡]
```

### Additional context / 其他信息

无

**Comment by LiangYong1216** [comment]
OOM了，显存不足呗，先看看目前有多少的空余显存：nvidia-smi，

**Comment by wm19999** [comment]
已经把batch_size改到最小了，其他的程序也都关了，按照readme中的介绍，4090，24G的显存使用AdvertiseGen.tar.gz数据集进行lora微调是没有问题的呀

**Comment by LiangYong1216** [comment]
在lora_finetune.sh文件中，去掉--fp16这个参数试试？

**Comment by wm19999** [comment]
> 在lora_finetune.sh文件中，去掉--fp16这个参数试试？

还是不行，会出现同样的报错

**Comment by LiangYong1216** [comment]
你看下你下载的模型是几个G的?
![image](https://github.com/OpenBMB/MiniCPM/assets/66230782/85d0b1df-26c5-46de-bf15-04686621f400)
这是我下载的，5.1个G，你看看你的多大？

**Comment by wm19999** [comment]
![image](https://github.com/OpenBMB/MiniCPM/assets/86055438/e8a78b61-bbca-44a3-a54a-db5db37af233)
我也一样5.08GB

**Comment by LiangYong1216** [comment]
那就没问题呀，代码的其他地方你还动过吗？

**Comment by wm19999** [comment]
![image](https://github.com/OpenBMB/MiniCPM/assets/86055438/4412453c-596b-4501-9058-b2ab66453c49)
我的git文件也有5个G

**Comment by wm19999** [comment]
> 那就没问题呀，代码的其他地方你还动过吗？

就是因为要在本地运行所以把文件路径给改了

**Comment by LiangYong1216** [comment]
git怎么这么大？备份到其他地方吧，然后再试试！我的才5KB

**Comment by wm19999** [comment]
在lora_finetune.sh文件中，需要修改配置文件，将其修改成：--deepspeed configs/ds_config_zero2.json

**Comment by LiangYong1216** [comment]
哈哈，我使用--deepspeed configs/ds_config_zero3.json可以跑，你能跑起来就行，跑出来的模型调用的结果可以看看嘛？

**Comment by wm19999** [comment]
> 哈哈，我使用--deepspeed configs/ds_config_zero3.json可以跑，你能跑起来就行，跑出来的模型调用的结果可以看看嘛？

可以呀，没问题可以交流交流，邮箱还是其他的方式？1282758228@qq.com

**Comment by LiangYong1216** [comment]
微调成功了吗？我的输出很差劲！！
