### ISSUE TITLE
[Bug]: 无法全量微调 MiniCPM-2B-sft-bf16的model，提示Flash Attention无法处理float32类型数据

### ISSUE THREAD

**Issue by Chenghao-Jia** [OpenBMB/MiniCPM#92]
### Is there an existing issue ? / 是否已有相关的 issue ?

- [X] I have searched, and there is no existing issue. / 我已经搜索过了，没有相关的 issue。

### Describe the bug / 描述这个 bug

错误
```
Flash Attention 2.0 only supports torch.float16 and torch.bfloat16 dtypes, but the current dype in MiniCPMModel is
torch.float32. You should run training or inference using Automatic Mixed-Precision via the `with
torch.autocast(device_type='torch_device'):` decorator, or load the model with the `torch_dtype` argument. Example:
`model = AutoModel.from_pretrained("openai/whisper-tiny", attn_implementation="flash_attention_2",
torch_dtype=torch.float16)`
Traceback (most recent call last):
  File "/sshfs/chenghao/model/MiniCPM/finetune/finetune.py", line 172, in <module>
    train_dataset = SupervisedDataset(
  File "/sshfs/chenghao/model/MiniCPM/finetune/finetune.py", line 61, in __init__
    item = self.preprocessing(self.data[0])
  File "/sshfs/chenghao/model/MiniCPM/finetune/finetune.py", line 78, in preprocessing
    for message in example["messages"]:
KeyError: 'messages'
```

### To Reproduce / 如何复现

命令行代码
```
formatted_time=$(date +"%Y%m%d")
echo $formatted_time


deepspeed --include localhost:4,5,6,7 finetune.py \
    --model_name_or_path /sshfs/pretrains/openbmb/MiniCPM-2B-sft-bf16/ \
    --output_dir output/OralCalculation_1/$formatted_time/ \
    --train_data_path data/OralCalculation_1_train.json \
    --eval_data_path data/OralCalculation_1_eval.json \
    --learning_rate 1e-3 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --bf16 True \
    --warmup_steps 100 \
    --max_steps 8000 \
    --weight_decay 0.01 \
    --use_lora \
    --evaluation_strategy steps \
    --eval_steps 500 \
    --save_strategy steps \
    --save_steps 500 \
    --seed 42 \
    --log_level info \
    --logging_strategy steps \
    --logging_steps 10 \
    --deepspeed configs/ds_config_zero2.json

```

### Environment / 环境

```shell
- CUDA: [CUDA 11.6]
- Device: [RTX3090]
```

**Comment by hitszxs** [comment]
为什么感觉是数据的问题

**Comment by cyx2000** [comment]
加载模型没有设置数据类型，用了默认的float32

**Comment by zh-zheng** [comment]
fixed in #106.

**Comment by lifelsl** [comment]
> fixed in #106.

兄弟你解决了吗，改怎么解决这个问题，能给个sh脚本文件截图吗
